-- Daily Punch Report data for Work Hour Approval
create table if not exists public.work_hour_daily_punch (
  id bigint generated by default as identity primary key,
  work_date date not null,
  employee_id bigint not null,
  employee_name text not null default '',
  designation text not null default '',
  doj text not null default '',
  department text not null default '',
  section text not null default '',
  line text not null default '',
  log_in text not null default '',
  log_out text not null default '',
  uploaded_by text not null default '',
  uploaded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint work_hour_daily_punch_unique unique (work_date, employee_id)
);
create index if not exists work_hour_daily_punch_work_date_idx on public.work_hour_daily_punch(work_date);
create index if not exists work_hour_daily_punch_department_idx on public.work_hour_daily_punch(department);
create index if not exists work_hour_daily_punch_section_idx on public.work_hour_daily_punch(section);
create index if not exists work_hour_daily_punch_line_idx on public.work_hour_daily_punch(line);
alter table public.work_hour_daily_punch enable row level security;
grant select, insert, update, delete on table public.work_hour_daily_punch to anon, authenticated;
grant usage, select on sequence public.work_hour_daily_punch_id_seq to anon, authenticated;
drop policy if exists "work_hour_daily_punch_select" on public.work_hour_daily_punch;
create policy "work_hour_daily_punch_select" on public.work_hour_daily_punch for select to anon, authenticated using (true);
drop policy if exists "work_hour_daily_punch_insert" on public.work_hour_daily_punch;
create policy "work_hour_daily_punch_insert" on public.work_hour_daily_punch for insert to anon, authenticated with check (true);
drop policy if exists "work_hour_daily_punch_update" on public.work_hour_daily_punch;
create policy "work_hour_daily_punch_update" on public.work_hour_daily_punch for update to anon, authenticated using (true) with check (true);
drop policy if exists "work_hour_daily_punch_delete" on public.work_hour_daily_punch;
create policy "work_hour_daily_punch_delete" on public.work_hour_daily_punch for delete to anon, authenticated using (true);
