-- Daily OT Cost data for Work Hour Approval
create table if not exists public.work_hour_ot_cost (
  id bigint generated by default as identity primary key,
  work_date date not null,
  employee_id bigint not null,
  employee_name text not null default '',
  department text not null default '',
  designation text not null default '',
  section text not null default '',
  line text not null default '',
  gross_salary numeric(14,2),
  ot_rate numeric(14,2),
  total_ot_hour numeric(10,2),
  regular_ot_hour numeric(10,2),
  extra_ot_hour numeric(10,2),
  regular_ot_cost numeric(14,2),
  extra_ot_cost numeric(14,2),
  total_ot_cost numeric(14,2),
  uploaded_by text not null default '',
  uploaded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint work_hour_ot_cost_daily_unique unique (work_date, employee_id)
);
create index if not exists work_hour_ot_cost_work_date_idx on public.work_hour_ot_cost(work_date);
create index if not exists work_hour_ot_cost_department_idx on public.work_hour_ot_cost(department);
create index if not exists work_hour_ot_cost_section_idx on public.work_hour_ot_cost(section);
create index if not exists work_hour_ot_cost_line_idx on public.work_hour_ot_cost(line);
alter table public.work_hour_ot_cost enable row level security;
grant select, insert, update, delete on table public.work_hour_ot_cost to anon, authenticated;
grant usage, select on sequence public.work_hour_ot_cost_id_seq to anon, authenticated;
drop policy if exists "work_hour_ot_cost_select" on public.work_hour_ot_cost;
create policy "work_hour_ot_cost_select" on public.work_hour_ot_cost for select to anon, authenticated using (true);
drop policy if exists "work_hour_ot_cost_insert" on public.work_hour_ot_cost;
create policy "work_hour_ot_cost_insert" on public.work_hour_ot_cost for insert to anon, authenticated with check (true);
drop policy if exists "work_hour_ot_cost_update" on public.work_hour_ot_cost;
create policy "work_hour_ot_cost_update" on public.work_hour_ot_cost for update to anon, authenticated using (true) with check (true);
drop policy if exists "work_hour_ot_cost_delete" on public.work_hour_ot_cost;
create policy "work_hour_ot_cost_delete" on public.work_hour_ot_cost for delete to anon, authenticated using (true);
