-- Department & Section master for Work Hour Approval
create table if not exists public.work_hour_department_sections (
  id bigint generated by default as identity primary key,
  department text not null,
  section text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint work_hour_department_sections_department_chk check (length(trim(department)) > 0),
  constraint work_hour_department_sections_section_chk check (length(trim(section)) > 0),
  constraint work_hour_department_sections_unique unique (department, section)
);
alter table public.work_hour_department_sections enable row level security;
grant select, insert, update, delete on table public.work_hour_department_sections to anon, authenticated;
grant usage, select on sequence public.work_hour_department_sections_id_seq to anon, authenticated;
drop policy if exists "work_hour_department_sections_select" on public.work_hour_department_sections;
create policy "work_hour_department_sections_select" on public.work_hour_department_sections for select to anon, authenticated using (true);
drop policy if exists "work_hour_department_sections_insert" on public.work_hour_department_sections;
create policy "work_hour_department_sections_insert" on public.work_hour_department_sections for insert to anon, authenticated with check (true);
drop policy if exists "work_hour_department_sections_update" on public.work_hour_department_sections;
create policy "work_hour_department_sections_update" on public.work_hour_department_sections for update to anon, authenticated using (true) with check (true);
drop policy if exists "work_hour_department_sections_delete" on public.work_hour_department_sections;
create policy "work_hour_department_sections_delete" on public.work_hour_department_sections for delete to anon, authenticated using (true);

insert into public.work_hour_department_sections (department, section, sort_order) values
('Cutting','Cutting',1),
('Embellishment','Embellishment',2),('Embellishment','Embroidery',3),('Embellishment','Printing',4),
('Embroidery','Embroidery',5),('Finishing','Finishing',6),
('HR, Admin & Compliance','Admin',7),('HR, Admin & Compliance','Compliance',8),('HR, Admin & Compliance','Human Resources',9),
('Industrial Engineering','Industrial Engineering',10),
('Maintenance','Maintenance',11),('Maintenance','Mechanical',12),('Maintenance','Utility',13),
('Material Control','Material Control',14),
('Pilot Run & Training Line','Pilot Run & Training Line',15),('Pilot Run & Training Line','Sewing',16),
('Printing','Printing',17),
('Product Development Center','Product Development Center',18),('Product Development Center','Sample',19),
('Quality Assurance','Cutting',20),('Quality Assurance','Embellishment',21),('Quality Assurance','Embroidery',22),('Quality Assurance','Finishing',23),('Quality Assurance','Material Control',24),('Quality Assurance','Printing',25),('Quality Assurance','Quality Assurance',26),('Quality Assurance','Sewing',27),
('Sewing','Finishing',28),('Sewing','Sewing',29)
on conflict (department, section) do update set sort_order=excluded.sort_order,updated_at=now();
