'use strict';
const SB_URL='https://hqlowjnbugaehpxrqtzc.supabase.co',SB_KEY='sb_publishable_CyiA3Ls1wbctt1VCc3DOAA_NeOfPCfx';
const tabNames={p1:'Work Hour Approval Request',p2:'Department-wise EOT & OT Status',p3:'Department & Section Setup',p4:'OT Cost Data',p5:'Daily Punch Report',p6:'Line & Level Settings',p7:'User Interface'};
let session=null,currentUser='',profile=null,users=[],editId=null,poll=null;
window.workHourAccess={};
let serverClock=null;window.workHourServerNow=()=>serverClock?new Date(serverClock.at+performance.now()-serverClock.tick):new Date();
const el=id=>document.getElementById(id);
const setupToken=new URLSearchParams(location.hash.slice(1)).get('setup');
if(setupToken){history.replaceState(null,'',location.pathname);el('setupFields').hidden=false;el('loginTitle').textContent='Set up Administrator';el('loginHint').textContent='Create the first administrator account. This private setup link can be used once.';el('signIn').textContent='Create Administrator';el('password').minLength=10;el('password').autocomplete='new-password';for(const id of ['setupName','setupDepartment','setupDesignation','setupOffice'])el(id).required=true;}
async function request(path,body,token){const r=await fetch(SB_URL+path,{method:'POST',headers:{apikey:SB_KEY,'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error_description||d.error||d.msg||d.message||'Request failed'),{status:r.status});return d;}
async function api(body){if(!session)throw Error('Please log in');if(Date.now()>session.expires_at-30000){const d=await request('/auth/v1/token?grant_type=refresh_token',{refresh_token:session.refresh_token});session={...d,expires_at:Date.now()+d.expires_in*1000};}try{return await request('/functions/v1/work-hour-access',body,session.access_token)}catch(e){if(e.status===401){logout();}throw e;}}
async function dbRequest(table,method,query='',body,prefer,context){return api({op:'data',table,method,query,body,prefer,context});}
async function notifySaved(){}
function applyProfile(p){if(p.server_now&&Number.isFinite(Date.parse(p.server_now)))serverClock={at:Date.parse(p.server_now),tick:performance.now()};profile=p;currentUser=p.user_name;window.workHourAccess=p;el('who').textContent=p.user_name+' · '+p.department+(!p.is_admin&&!Object.values(p.permissions||{}).some(x=>x.view)?' · No tabs assigned — contact Administrator':'');el('openUsers').hidden=!p.is_admin;try{el('dashboard').contentWindow.whApplyAccess?.()}catch(e){}}
async function login(){const d=await request('/auth/v1/token?grant_type=password',{email:el('email').value.trim(),password:el('password').value});session={...d,expires_at:Date.now()+d.expires_in*1000};try{applyProfile(await api({op:'me'}));}catch(e){session=null;throw e;}el('password').value='';el('login').style.display='none';el('app').style.display='block';el('manage').style.display='none';el('dashboard').style.display='block';el('logout').hidden=false;await bridgeReady;el('dashboard').src='work_hour_approval_dashboard.html?build=20261007_8';poll=setInterval(async()=>{try{const p=await api({op:'me'});applyProfile(p);}catch(e){logout();el('loginMessage').textContent=e.message;}},15000);}
function logout(){if(poll)clearInterval(poll);if(session)fetch(SB_URL+'/auth/v1/logout',{method:'POST',headers:{apikey:SB_KEY,Authorization:'Bearer '+session.access_token}}).catch(()=>{});session=null;profile=null;window.workHourAccess={};currentUser='';el('dashboard').src='about:blank';el('app').style.display='none';el('login').style.display='block';el('logout').hidden=true;el('who').textContent='';el('loginMessage').textContent='';}
el('logout').onclick=logout;
el('loginForm').onsubmit=async e=>{e.preventDefault();el('signIn').disabled=true;el('loginMessage').textContent='';try{if(setupToken&&!el('setupFields').hidden){await request('/functions/v1/work-hour-access',{op:'setup',token:setupToken,email:el('email').value,password:el('password').value,user_name:el('setupName').value,department:el('setupDepartment').value,section:el('setupSection').value,designation:el('setupDesignation').value,office_id:el('setupOffice').value});el('setupFields').hidden=true;for(const id of ['setupName','setupDepartment','setupDesignation','setupOffice'])el(id).required=false;el('loginTitle').textContent='Sign in';el('signIn').textContent='Login';}await login();}catch(e){el('loginMessage').textContent=e.message;}finally{el('signIn').disabled=false;}};
el('openReport').onclick=()=>{el('manage').style.display='none';el('dashboard').style.display='block';};
el('openUsers').onclick=async()=>{if(!profile?.is_admin)return;el('dashboard').style.display='none';el('manage').style.display='block';try{await listUsers();const ds=await dbRequest('work_hour_department_sections','GET','select=department,section&order=sort_order.asc');for(const [id,key] of [['departments','department'],['sections','section']])el(id).replaceChildren(...[...new Set(ds.map(r=>r[key]))].map(v=>{const o=document.createElement('option');o.value=v;return o;}));scopeOptions=ds;const state=await workHourApprovalLoadState();scopeLevels=[...new Set(state.R.filter(r=>r.k==='L').map(r=>r.lv))];newUser();}catch(e){el('userMessage').textContent=e.message;}};
async function listUsers(){users=await api({op:'users'});el('userList').replaceChildren(...users.map(u=>{const b=document.createElement('button');b.className='user';b.type='button';b.textContent=u.user_name;const s=document.createElement('small');s.textContent=u.email+' · '+(u.is_admin?'Administrator':u.active?'Active':'Disabled');b.append(s);b.disabled=u.is_admin;b.onclick=()=>editUser(u);return b;}));}
function permissions(p={}){el('permissionRows').replaceChildren(...Object.entries(tabNames).map(([tab,name])=>{const tr=document.createElement('tr'),title=document.createElement('td');title.textContent=name;tr.append(title);for(const action of ['view','edit','delete','export']){const td=document.createElement('td'),c=document.createElement('input');c.type='checkbox';c.dataset.tab=tab;c.dataset.action=action;c.checked=p[tab]?.[action]===true;c.setAttribute('aria-label',name+' '+action);const editable=['p3','p4','p5','p6','p7'].includes(tab),deletable=['p3','p6'].includes(tab);c.disabled=(action==='edit'&&!editable)||(action==='delete'&&!deletable);c.onchange=()=>{const cells=tr.querySelectorAll('input');if(action==='view'&&!c.checked)cells.forEach(x=>x.checked=false);if(action!=='view'&&c.checked)cells[0].checked=true;if(action==='delete'&&c.checked)cells[1].checked=true;};td.append(c);tr.append(td);}return tr;}));}
function newUser(){editId=null;el('userForm').reset();el('editTitle').textContent='Add User';el('passwordHint').textContent='(min. 10 characters)';el('userForm').elements.password.required=true;el('userMessage').textContent='';permissions();drawEntryScope({mode:'selected',rules:[]});}
function editUser(u){editId=u.id;el('userForm').reset();for(const k of ['email','user_name','department','section','designation','office_id'])el('userForm').elements[k].value=u[k]||'';el('userForm').elements.active.checked=u.active;el('userForm').elements.password.required=false;el('passwordHint').textContent='(leave blank to keep current password)';el('editTitle').textContent='Edit '+u.user_name;el('userMessage').textContent='';permissions(u.permissions);drawEntryScope(u.permissions?.p7?.entry_scope||{mode:'all',rules:[]});}
el('newUser').onclick=newUser;
el('userForm').onsubmit=async e=>{e.preventDefault();el('saveUser').disabled=true;el('userMessage').textContent='';try{const b=Object.fromEntries(new FormData(e.target));b.id=editId;b.active=e.target.elements.active.checked;b.permissions={};el('permissionRows').querySelectorAll('input').forEach(c=>{(b.permissions[c.dataset.tab]??={})[c.dataset.action]=c.checked&&!c.disabled;});b.entry_scope=readEntryScope();const user=await api({op:'save-user',...b});await listUsers();editUser(user);el('userMessage').textContent='User and tab access saved.';}catch(e){el('userMessage').textContent=e.message;}finally{el('saveUser').disabled=false;}};
// Load the same SQL-backed report bridge after these authenticated helpers exist.
const bridge=document.createElement('script');const bridgeReady=new Promise((resolve,reject)=>{bridge.onload=resolve;bridge.onerror=()=>reject(Error('Report bridge could not load. Refresh and retry.'));});bridge.src='work_hour_bridge.js?build=20261007_8';document.head.append(bridge);

let scopeOptions=[],scopeLevels=[];
function option(value,label=value){const o=document.createElement('option');o.value=value;o.textContent=label;return o;}
function addEntryScope(rule={department:'',section:'*',level:'*'}){
 const div=document.createElement('div');div.className='scope-rule';
 const dept=document.createElement('select'),section=document.createElement('select'),level=document.createElement('select'),remove=document.createElement('button');
 dept.dataset.scope='department';section.dataset.scope='section';level.dataset.scope='level';
 for(const [input,label] of [[dept,'Allowed Department'],[section,'Allowed Section'],[level,'Allowed Level']])input.setAttribute('aria-label',label);
 dept.replaceChildren(option('','Choose Department'),...[...new Set(scopeOptions.map(r=>r.department))].map(d=>option(d)));
 dept.value=rule.department;
 function sections(){const old=section.value;section.replaceChildren(option('*','All sections'),...[...new Set(scopeOptions.filter(x=>x.department===dept.value).map(x=>x.section))].map(s=>option(s)));section.value=Array.from(section.options).some(o=>o.value===old)?old:'*';}
 sections();section.value=rule.section;
 level.replaceChildren(option('*','All levels (including no level)'),option('','No Level'),...scopeLevels.map(l=>option(l)));level.value=rule.level;
 dept.onchange=sections;remove.type='button';remove.textContent='Remove';remove.onclick=()=>div.remove();
 div.append(dept,section,level,remove);el('scopeRules').append(div);
}
function drawEntryScope(scope){el('scopeAll').checked=scope.mode==='all';el('scopeRules').replaceChildren();(scope.rules||[]).forEach(addEntryScope);scopeControls();}
function scopeControls(){const all=el('scopeAll').checked;el('scopeRules').hidden=all;el('addScope').hidden=all;}
function readEntryScope(){return {mode:el('scopeAll').checked?'all':'selected',rules:Array.from(el('scopeRules').children).map(div=>Object.fromEntries(Array.from(div.querySelectorAll('select')).map(s=>[s.dataset.scope,s.value])))};}
el('scopeAll').onchange=scopeControls;el('addScope').onclick=()=>addEntryScope();
