import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
try{
 await db.exec(`
 create role anon;create role authenticated;create role service_role bypassrls;
 create table public.users(id integer,name text unique,password text,color text);
 create table public.module_access(username text,modules text);
 create table public.tasks(sl integer primary key,task text,person text,actual_date text);
 create table public.work_hour_accounts(id uuid primary key,user_name text,active boolean,is_admin boolean);
 create table public.work_hour_user_interface(id uuid primary key,work_date date,department text,present_manpower integer);
 create table public.work_hour_ot_cost(id integer,work_date date,department text,total_ot_hour numeric);
 insert into public.users values(1,'admin','admin-test-password','#fff'),(2,'user','user-test-password','#000');
 insert into public.module_access values('user','overview');
 insert into public.tasks values(1,'Old task','user','');
 insert into public.work_hour_accounts values('10000000-0000-0000-0000-000000000001','WH Admin',true,true),('10000000-0000-0000-0000-000000000002','WH User',true,false);
 insert into public.work_hour_user_interface values('20000000-0000-0000-0000-000000000001','2026-10-08','Sewing',20);
 grant all on all tables in schema public to service_role;
 `);
 await db.exec(await fs.readFile(new URL('../../database/admin_publication_schema.sql',import.meta.url),'utf8'));
 const call=async(sql,params=[]) => (await db.query(sql,params)).rows[0]?.result;
 const hashA='a'.repeat(64),hashU='b'.repeat(64);
 await db.exec('set role service_role');
 assert.equal((await call('select public.datacell_login($1,$2,$3) result',['admin','wrong',hashA])).status,401);
 assert.equal((await call('select public.datacell_login($1,$2,$3) result',['admin','admin-test-password',hashA])).name,'admin');
 await call('select public.datacell_login($1,$2,$3) result',['user','user-test-password',hashU]);
 await assert.rejects(call('select public.datacell_publish($1,$2,null) result',['datacell',hashU]),/Administrator/);
 await assert.rejects(call('select public.datacell_publish($1,$2,null) result',['work-hour','10000000-0000-0000-0000-000000000002']),/Administrator/);
 const first=await call('select public.datacell_publish($1,$2,null) result',['datacell',hashA]);
 assert(first.version);
 const read=(table,query={},version=first.version)=>call('select public.datacell_read_published($1,$2,$3) result',[table,JSON.stringify(query),version]);
 assert.equal((await read('tasks'))[0].task,'Old task');
 await db.exec("update public.tasks set task='New task';update public.work_hour_user_interface set present_manpower=30;");
 assert.equal((await read('tasks'))[0].task,'Old task');
 assert.equal((await read('work_hour_user_interface',{select:'department,present_manpower',work_date:'eq.2026-10-08'}))[0].present_manpower,20);
 await assert.rejects(read('users'),/Unsupported report source/);
 await assert.rejects(read('tasks',{select:'password'}),/Unsupported report column/);
 await assert.rejects(read('tasks',{'sl;drop table users':'eq.1'}),/Unsupported report filter/);
 assert.deepEqual(await read('tasks',{task:"eq.' or true --"}),[]);
 await assert.rejects(call('select public.datacell_publish($1,$2,null) result',['datacell',hashA]),/another administrator/);
 const second=await call('select public.datacell_publish($1,$2,$3) result',['work-hour','10000000-0000-0000-0000-000000000001',first.version]);
 assert.equal((await read('tasks',{},second.version))[0].task,'New task');
 assert.equal((await read('work_hour_user_interface',{},second.version))[0].present_manpower,30);
 assert.equal((await read('tasks',{},first.version))[0].task,'Old task','previous pinned version remains consistent');
 await db.exec("update public.users set password='changed' where name='user'");
 await assert.rejects(call('select public.datacell_session($1) result',[hashU]),/Please log in/);
 await call('select public.datacell_logout($1) result',[hashA]);
 await assert.rejects(call('select public.datacell_session($1) result',[hashA]),/Please log in/);
 await db.exec('set role anon');
 await assert.rejects(call('select public.datacell_publication_head() result'),/permission denied/);
 await assert.rejects(db.query('select * from datacell_publication_private.tasks'),/permission denied/);
 await db.exec('reset role');
 const grants=await db.query("select has_function_privilege('anon','public.datacell_publish(text,text,uuid)','EXECUTE') allowed");
 assert.equal(grants.rows[0].allowed,false);
 console.log('PASS: PostgreSQL schema, server-side login, admin-only atomic publication, unchanged reports before publish, typed date/projection queries, SQL injection rejection, version pinning, credential revocation, logout and private grants.');
}finally{await db.close();}
